spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://${db.hostname}:3306/delivery
    username: root
    password: password

  flyway:
    url: jdbc:mysql://${db.hostname}:3306/delivery
    user: root
    password: password

  jpa:
    hibernate:
      ddl-auto: validate

  redis:
    host: ${redis.hostname}
    password:
    port: 6379

  session:
    store-type: redis # 이 설정으로 @EnableRedisHttpSession 을 대체함.
    
server:
  servlet:
    session:
      timeout: -1m

db:
  hostname: db-mysql # Docker container에서 localhost는 was 자신이 되기때문에 docker db 호스트 이름을 적어줘야함.
redis:
  hostname: redis