spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/testdb
    username: root
    password: password
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none # ddl 자동 생성을 db migration 때 하기 위함

mybatis:
  type-aliases-package: com/deliver
  mapper-locations: classpath:mybatis/mapper/*.xml
