spring:
  datasource:
    # 쿼리 로그가 2중으로 찍히는데, log4jdbc는 정리가 안되어 나와서 주석처리함. mybatis 쿼리로그를 보려면 이 driver-class-name 사용
    # driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    encoding: UTF-8

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  profiles:
    active: dev

mybatis:
  mapper-locations: mybatis/mapper/*.xml
  type-aliases-package:
    com.bluedelivery.domain.shop,
    com.bluedelivery.domain.category,
    com.bluedelivery.shop.businesshour,
    com.bluedelivery.shop.closingday,
    com.bluedelivery.shop.suspension,
    com.bluedelivery.user.domain,
    com.bluedelivery.utility,
    org.apache.ibatis.type
