spring:
  datasource:
    url: jdbc:h2:mem://localhost:3306/test;MODE=MYSQL;DB_CLOSE_DELAY=-1
    user: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    url: jdbc:h2:mem://localhost:3306/test;MODE=MYSQL;DB_CLOSE_DELAY=-1
    user: sa

  cache:
    type: simple
