spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none # ddl 자동 생성을 db migration 때 하기 위함
  flyway:
    baseline-on-migrate: true
    encoding: UTF-8
    ignore-ignored-migrations: true
    clean-on-validation-error: true
  h2:
    console:
      enabled: true

mybatis:
  mapper-locations: mybatis/mapper/*.xml
  type-aliases-package:
    com.delivery.shop.shop,
    com.delivery.shop.category,
    com.delivery.shop.businesshour,
    com.delivery.shop.closingday,
    com.delivery.shop.suspension,
    com.delivery.user,
    com.delivery.utility,
    org.apache.ibatis.type
