spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/delivery
    username: root
    password: password
  flyway:
    ignore-ignored-migrations: true
    clean-on-validation-error: true
    url: jdbc:mysql://localhost:3306/delivery
    user: root
    password: password
