spring:
  datasource:
    url: jdbc:mysql://localhost:3306/delivery
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none

mybatis:
  type-aliases-package: com/deliver
  mapper-locations: classpath:mybatis/mapper/*.xml
