spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem://localhost:3306/test;MODE=MYSQL;DB_CLOSE_DELAY=-1
    user: sa
    password:

  flyway:
    enabled: false
    url: jdbc:h2:mem://localhost:3306/test;MODE=MYSQL;DB_CLOSE_DELAY=-1
    user: sa

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true

  session:
    store-type: none

  redis:
    host: localhost
    password:
    port: 6379

kafka:
  bootstrap:
    server: localhost:29092

