spring:
  datasource:
    url: jdbc:mysql://localhost3306/test
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev

mybatis:
  type-aliases-package: com/deliver
  mapper-locations: resources/mybatis/mapper/**/*.xml
