spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:log4jdbc:mysql://${db.hostname}:3306/delivery
    username: root
    password: password
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  flyway:
    url: jdbc:mysql://${db.hostname}:3306/delivery
    user: root
    password: password

db:
  hostname: db-mysql # Docker container에서 localhost는 was 자신이 되기때문에 docker db 호스트 이름을 적어줘야함.