spring:
  profiles:
    active: dev
  flyway:
    baseline-on-migrate: true
    encoding: UTF-8
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    properties:
      hibernate:
        format_sql: true

mybatis:
  mapper-locations: mybatis/mapper/*.xml
  type-aliases-package:
    com.delivery.shop.shop,
    com.delivery.shop.category,
    com.delivery.shop.businesshour,
    com.delivery.shop.closingday,
    com.delivery.shop.suspension,
    com.delivery.user,
    com.delivery.utility,
    org.apache.ibatis.type
