spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/delivery
    username: root
    password: password
  flyway:
    url: jdbc:mysql://localhost:3306/delivery
    user: root
    password: password
