spring:
  datasource:
    # 쿼리 로그가 2중으로 찍히는데, log4jdbc는 정리가 안되어 나와서 주석처리함. mybatis 쿼리로그를 보려면 이 driver-class-name 사용
    # driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    encoding: UTF-8

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  profiles:
    active: dev

# spring actuator
management:
  endpoints:
    web:
      exposure:
        include: # 보여주고 싶은 application 정보들
          - "info"
          - "health"
          - "flyway"
          - "metrics"
          - "scheduledtasks"
      base-path: /application
      path-mapping:
        health: healthcheck

  health:
    diskspace:
      enabled: false

  endpoint:
    health:
      show-details: always #Application에서 의존하고 있는 시스템의 healthCheck 정보 포함(mysql, redis 등)

  info: # info에 git 정보 포함
    git:
      mode: simple # simple or pull

mybatis:
  mapper-locations: mybatis/mapper/*.xml
  type-aliases-package:
    com.bluedelivery.domain.shop,
    com.bluedelivery.domain.category,
    com.bluedelivery.application.shop.businesshour,
    com.bluedelivery.domain.closingday,
    com.bluedelivery.domain.suspension,
    com.bluedelivery.user.domain,
    com.bluedelivery.utility,
    org.apache.ibatis.type
