spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/${db_dbname}
    username: ${db_username}
    password: ${db_password}
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  flyway:
    url: jdbc:mysql://localhost:3306/${db_dbname}
    user: ${db_username}
    password: ${db_password}
