spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/delivery
    username: root
    password: password
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  flyway:
    url: jdbc:mysql://localhost:3306/delivery
    user: root
    password: password
