RENAME TABLE RESTAURANTS TO RESTAURANT;

ALTER TABLE RESTAURANT ADD COLUMN INTRODUCE varchar(500);
ALTER TABLE RESTAURANT ADD COLUMN phone varchar(14);
ALTER TABLE RESTAURANT ADD COLUMN DELIVERY_AREA_GUIDE varchar(500);

CREATE TABLE BUSINESS_HOUR
(
    ID          INT AUTO_INCREMENT,
    REST_ID     INT,
    OPEN        TIME,
    CLOSE       TIME,
    DAY_OF_WEEK VARCHAR(50),
    PRIMARY KEY (ID),
    FOREIGN KEY (REST_ID) REFERENCES RESTAURANT (ID)
);

INSERT INTO RESTAURANT (NAME) VALUES ('BBQ 효자동점');
