ALTER TABLE MENU ADD COMPOSITION VARCHAR(100);
ALTER TABLE MENU ADD CONTENT VARCHAR(100);
ALTER TABLE MENU ADD CREATE_AT DATE;
ALTER TABLE MENU ADD MODIFIED_AT DATE;
ALTER TABLE MENU ADD STATUS VARCHAR(50);

CREATE INDEX idx_name on MENU (NAME);
