CREATE TABLE CATEGORY
(
    ID   INT,
    NAME VARCHAR(10) UNIQUE KEY,
    ENUM_NAME VARCHAR(20) UNIQUE KEY,
    PRIMARY KEY (ID)
);

CREATE TABLE CATEGORY_SHOP
(
    CATEGORY_ID INT,
    SHOP_ID INT,
    PRIMARY KEY (CATEGORY_ID, SHOP_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID),
    FOREIGN KEY (SHOP_ID) REFERENCES CATEGORY (ID)
)