ALTER TABLE MENU ADD GROUP_ID INT NOT NULL;
ALTER TABLE MENU ADD COMPOSITION VARCHAR(100);
ALTER TABLE MENU ADD CONTENT VARCHAR(100);
ALTER TABLE MENU ADD CREATE_AT DATE;
ALTER TABLE MENU ADD MODIFIED_AT DATE;
ALTER TABLE MENU ADD STATUS VARCHAR(50);

ALTER TABLE MENU ADD FOREIGN KEY (GROUP_ID) REFERENCES MENU_GROUP(ID);

CREATE INDEX idx_name on MENU (NAME);
