DROP TABLE IF EXISTS BUSINESS_HOURS;
DROP TABLE IF EXISTS RESTAURANTS;

CREATE TABLE RESTAURANTS
(
    ID   INT AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    INTRODUCE VARCHAR(200),
    PRIMARY KEY (ID)
);

CREATE TABLE BUSINESS_HOURS
(
    ID       INT AUTO_INCREMENT,
    REST_ID  INT,
    OPEN     TIME,
    CLOSE    TIME,
    DAY_TYPE VARCHAR(50),
    BUSINESS_HOUR_TYPE varchar(50),
    PRIMARY KEY (ID),
    FOREIGN KEY (REST_ID) REFERENCES RESTAURANTS(ID)
);