DROP TABLE IF EXISTS BUSINESS_HOURS;
DROP TABLE IF EXISTS RESTAURANTS;

CREATE TABLE RESTAURANTS
(
    ID                  INT AUTO_INCREMENT,
    NAME                VARCHAR(100) NOT NULL,
    INTRODUCE           VARCHAR(500),
    PHONE               VARCHAR(14),
    DELIVERY_AREA_GUIDE VARCHAR(500),
    PRIMARY KEY (ID)
);

CREATE TABLE BUSINESS_HOURS
(
    ID          INT AUTO_INCREMENT,
    REST_ID     INT,
    OPEN        TIME,
    CLOSE       TIME,
    DAY_OF_WEEK VARCHAR(50),
    PRIMARY KEY (ID),
    FOREIGN KEY (REST_ID) REFERENCES RESTAURANTS (ID)
);