INSERT INTO CATEGORY (ID, NAME, ENUM_NAME) VALUES (1, '한식', 'KOREAN');
INSERT INTO CATEGORY (ID, NAME, ENUM_NAME) VALUES (2, '중식', 'CHINESE');
INSERT INTO CATEGORY (ID, NAME, ENUM_NAME) VALUES (3, '일식', 'JAPANESE');
INSERT INTO CATEGORY (ID, NAME, ENUM_NAME) VALUES (4, '치킨', 'CHICKEN');
INSERT INTO CATEGORY (ID, NAME, ENUM_NAME) VALUES (5, '피자', 'PIZZA');
INSERT INTO CATEGORY (ID, NAME, ENUM_NAME) VALUES (6, '패스트푸드', 'FAST_FOOD');

INSERT INTO SHOP (NAME, PHONE) VALUES ('도깨비한방통닭', '0212341234'); -- 2
INSERT INTO SHOP (NAME, PHONE) VALUES ('교촌치킨 광화문점', '0238382929'); -- 3
INSERT INTO SHOP (NAME, PHONE) VALUES ('지노스피자', '0243214321'); -- 4
INSERT INTO SHOP (NAME, PHONE) VALUES ('칸다소바', '0299998888'); -- 5
INSERT INTO SHOP (NAME, PHONE) VALUES ('도미노피자 서울역점', '025556677'); -- 6
INSERT INTO SHOP (NAME, PHONE) VALUES ('버거파크', '023445567'); -- 7
INSERT INTO SHOP (NAME, PHONE) VALUES ('맛있다백반', '025559999'); -- 8

INSERT INTO CATEGORY_SHOP (CATEGORY_ID, SHOP_ID) VALUES (4, 1);
INSERT INTO CATEGORY_SHOP (CATEGORY_ID, SHOP_ID) VALUES (4, 2);
INSERT INTO CATEGORY_SHOP (CATEGORY_ID, SHOP_ID) VALUES (4, 3);
INSERT INTO CATEGORY_SHOP (CATEGORY_ID, SHOP_ID) VALUES (5, 4);
INSERT INTO CATEGORY_SHOP (CATEGORY_ID, SHOP_ID) VALUES (3, 5);
INSERT INTO CATEGORY_SHOP (CATEGORY_ID, SHOP_ID) VALUES (5, 6);
INSERT INTO CATEGORY_SHOP (CATEGORY_ID, SHOP_ID) VALUES (6, 7);
INSERT INTO CATEGORY_SHOP (CATEGORY_ID, SHOP_ID) VALUES (1, 8);