CREATE TABLE OPTION_GROUP
(
    OPTION_GROUP_ID INT AUTO_INCREMENT,
    MENU_ID INT,
    NAME VARCHAR(20),
    OPTION_REQUIRED BOOLEAN,
    MINIMUM_OPTION INT,
    MAXIMUM_OPTION INT,
    PRIMARY KEY (OPTION_GROUP_ID)
);

CREATE TABLE OPTIONS
(
    OPTION_ID INT AUTO_INCREMENT,
    NAME VARCHAR(20),
    PRICE INT,
    OPTION_GROUP_ID INT,
    PRIMARY KEY (OPTION_ID),
    FOREIGN KEY (OPTION_GROUP_ID) REFERENCES OPTION_GROUP (OPTION_GROUP_ID)
);
