CREATE TABLE USER (
    ID INT AUTO_INCREMENT,
    EMAIL VARCHAR(20) UNIQUE,
    PHONE VARCHAR(14) UNIQUE,
    PASSWORD VARCHAR(20),
    NICKNAME VARCHAR(30) UNIQUE,
    DATE_OF_BIRTH DATE,
    ADDRESS VARCHAR(100),
    PRIMARY KEY (ID)
)