CREATE TABLE CATEGORY
(
    ID   INT AUTO_INCREMENT,
    NAME VARCHAR(10) UNIQUE KEY,
    PRIMARY KEY (ID)
);

INSERT INTO CATEGORY (NAME) VALUES ('한식');
INSERT INTO CATEGORY (NAME) VALUES ('중식');
INSERT INTO CATEGORY (NAME) VALUES ('일식');
INSERT INTO CATEGORY (NAME) VALUES ('치킨');
INSERT INTO CATEGORY (NAME) VALUES ('피자');
INSERT INTO CATEGORY (NAME) VALUES ('패스트푸드');